
# This file is automatically generated, you probably don't want to edit this

qqplotOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "qqplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL, ...) {

            super$initialize(
                package='qqplots',
                name='qqplot',
                requiresData=TRUE,
                ...)
        
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "continuous",
                    "nominal",
                    "ordinal"))
        
            self$.addOption(private$..vars)
        }),
    active = list(
        vars = function() private$..vars$value),
    private = list(
        ..vars = NA)
)

qqplotResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        qqPlots = function() private$.items[["qqPlots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Q-Q Normal Plot")
            self$add(jmvcore::Array$new(
                options=options,
                name="qqPlots",
                title="Q-Q Normal Plots",
                items="(vars)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=450,
                    height=400,
                    renderFun=".qqPlot",
                    clearWith=list())))}))

qqplotBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "qqplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'qqplots',
                name = 'qqplot',
                version = c(1,0,0),
                options = options,
                results = qqplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Q-Q Normal Plot
#'
#' 
#' @param data .
#' @param vars .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$qqPlots} \tab \tab \tab \tab \tab an array of the Q-Q plots \cr
#' }
#'
#' @export
qqplot <- function(
    data,
    vars) {

    if ( ! requireNamespace('jmvcore'))
        stop('qqplot requires jmvcore to be installed (restart may be required)')

    options <- qqplotOptions$new(
        vars = vars)

    results <- qqplotResults$new(
        options = options)

    analysis <- qqplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
