
# This file is automatically generated, you probably don't want to edit this

qqplotOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "qqplotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL, ...) {

            super$initialize(
                package='qqplots',
                name='qqplot',
                requiresData=TRUE,
                ...)
        
            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var)
        
            self$.addOption(private$..var)
        }),
    active = list(
        var = function() private$..var$value),
    private = list(
        ..var = NA)
)

qqplotResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$..plot),
    private = list(
        ..plot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Q-Q Normal Plot")
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Q-Q Normal Plot",
                width=300,
                height=400,
                renderFun=".plot")
            self$add(private$..plot)}))

qqplotBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "qqplotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'qqplots',
                name = 'qqplot',
                version = c(1,0,0),
                options = options,
                results = qqplotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Q-Q Normal Plot
#'
#' 
#' @param data .
#' @param var .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
qqplot <- function(
    data,
    var) {

    if ( ! requireNamespace('jmvcore'))
        stop('qqplot requires jmvcore to be installed (restart may be required)')

    options <- qqplotOptions$new(
        var = var)

    results <- qqplotResults$new(
        options = options)

    analysis <- qqplotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
